name: service a

on:
    workflow_call:
    repository_dispatch:


jobs:
    test:
        if: false
        uses: ./.github/workflows/test-pipeline.yml
    build:
        uses: ./.github/workflows/build-pipeline.yml
        with:
            can-run: false
    run-service:
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - name: echo the name
              run: echo "service a"