name: service a

on:
    workflow_call:
    repository_dispatch:


jobs:
    test:
        if: false
        uses: ./.github/workflows/test-pipeline.yml
    build:
        uses: ./.github/workflows/build-pipeline.yml
    run-service:
        needs: [test,build]
        if: ${{ needs.test.result != 'failure' }}
        runs-on: ubuntu-latest
        steps:
            - name: echo the name
              run: echo "service a"