name: service a

on:
    workflow_call:
    repository_dispatch:


jobs:
    build:
        uses: ./.github/workflows/build-pipeline.yml
    run-service:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: echo the name
              run: echo "service a"